package formValidationSectionTestCases;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.Select;
import org.testng.annotations.Test;

import commonBaseData.Base;

public class CheckOut_Form_Form_Validation extends Base{
	@Test
	public void Check_All_textbox_which_come_into_CheckOut_Page_Checkout_Form_Validation_Test() throws InterruptedException {
		
		JavascriptExecutor jse = (JavascriptExecutor)driver;
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		/*driver.findElement(By.xpath("//ul[@class='links']//a[contains(text(),'Sign in')]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='email']")).clear();
		driver.findElement(By.xpath("//input[@id='email']")).sendKeys("sajid.shekh@rugartisan.com");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@id='password']")).clear();
		driver.findElement(By.xpath("//input[@id='password']")).sendKeys("Sajid01$");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[@id='btn-submit']//span[contains(text(),'Login')]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//img[@alt='shopping bag']")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("//a[@title='Remove This Item']")).click();
		driver.findElement(By.xpath("//*[@id=\"navbarResponsive\"]/div/div[1]/div/div[2]/ul/li/div/a")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[normalize-space()='+ New Address']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).clear();
		Thread.sleep(1000);
		WebElement drpco = driver.findElement(By.id("shipping_country"));
		Select sel = new Select(drpco);
		sel.selectByValue("United Kingdom");
		Thread.sleep(2000);
		WebElement drpst = driver.findElement(By.id("shipping_state"));
		Select selsta = new Select(drpst);
		selsta.selectByValue("Antrim");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).clear();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[normalize-space()='Place Order']")).click();
		Thread.sleep(2000);
		
		
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).sendKeys("SajidSajidSajidSajid");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).sendKeys("ShekhShekhShekhShekh");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).sendKeys("8390057538");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).sendKeys("rugArtisanrugArtisanrugArtisanrug");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).sendKeys("272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London ");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).sendKeys("272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London ");
		
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).sendKeys("London");
		Thread.sleep(2000);
		WebElement drpco1 = driver.findElement(By.id("shipping_country"));
		Select sel1 = new Select(drpco1);
		sel1.selectByValue("United Kingdom");
		Thread.sleep(2000);
		WebElement drpst1 = driver.findElement(By.id("shipping_state"));
		Select selsta1 = new Select(drpst1);
		selsta1.selectByValue("Antrim");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).sendKeys("SW10 9EW");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[normalize-space()='Place Order']")).click();
		Thread.sleep(2000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).clear();
		Thread.sleep(2000);
		
		
		
		
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).sendKeys("SajidSajidSajidSajidSajidSajidSajidSajid");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).sendKeys("ShekhShekhShekhShekhSajidSajidSajidSajid");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).sendKeys("8390057538");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).sendKeys("rugArtisanrugArtisanrugArtisanrugSajidSajidSajidSajid");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).sendKeys("272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London , ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).sendKeys("272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London , ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London");
		
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).sendKeys("London");
		Thread.sleep(2000);
		WebElement drpco2 = driver.findElement(By.id("shipping_country"));
		Select sel2 = new Select(drpco2);
		sel2.selectByValue("United Kingdom");
		Thread.sleep(2000);
		WebElement drpst2 = driver.findElement(By.id("shipping_state"));
		Select selsta2 = new Select(drpst2);
		selsta2.selectByValue("Aberdeen City");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).sendKeys("AB24");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[normalize-space()='Place Order']")).click();
		Thread.sleep(20000);
		
		
		
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).clear();
		Thread.sleep(2000);
		
		
		
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).sendKeys("SajidSajid!@!@!@@");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).sendKeys("Sajid@$@#");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).sendKeys("8390057538@##");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).sendKeys("rdSajidSajid@##@#!##!##");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).sendKeys(" ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London , ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).sendKeys(" 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London , ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London");
		
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).sendKeys("London@#!#!#!@");
		Thread.sleep(2000);
		WebElement drpco3 = driver.findElement(By.id("shipping_country"));
		Select sel3 = new Select(drpco3);
		sel3.selectByValue("United Kingdom");
		Thread.sleep(2000);
		WebElement drpst3 = driver.findElement(By.id("shipping_state"));
		Select selsta3 = new Select(drpst3);
		selsta3.selectByValue("Aberdeen City");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).sendKeys("AB24@@##!");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[normalize-space()='Place Order']")).click();
		Thread.sleep(20000);
		
		
		
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).clear();
		Thread.sleep(2000);
		
		
		
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).sendKeys("Sajid131312313");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).sendKeys("Sajid231231");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).sendKeys("8390057538");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).sendKeys("ajidSajidSajidSajid23213");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).sendKeys(" Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London , ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).sendKeys(" ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London , ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon 272 Fulham Road, ChelseaLondon London London");
		
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).sendKeys("London");
		Thread.sleep(2000);
		WebElement drpco5 = driver.findElement(By.id("shipping_country"));
		Select sel5 = new Select(drpco5);
		sel5.selectByValue("United Kingdom");
		Thread.sleep(2000);
		WebElement drpst5 = driver.findElement(By.id("shipping_state"));
		Select selsta5 = new Select(drpst5);
		selsta5.selectByValue("Aberdeen City");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).sendKeys("AB24");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[normalize-space()='Place Order']")).click();
		Thread.sleep(20000);
		
		
		
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).clear();
		Thread.sleep(2000);
		
		
		
		
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).sendKeys("00000000000");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).sendKeys("0000000000");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).sendKeys("0000000000");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).sendKeys("0000000000000");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).sendKeys("000000000000000000000000000");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).sendKeys("0000000000000000000000000");
		
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).sendKeys("00000000");
		Thread.sleep(2000);
		WebElement drpco6 = driver.findElement(By.id("shipping_country"));
		Select sel6 = new Select(drpco6);
		sel6.selectByValue("United Kingdom");
		Thread.sleep(2000);
		WebElement drpst6 = driver.findElement(By.id("shipping_state"));
		Select selsta6 = new Select(drpst6);
		selsta6.selectByValue("Aberdeen City");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).sendKeys("00000000000");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[normalize-space()='Place Order']")).click();
		Thread.sleep(20000);
		
		
		
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).clear();
		Thread.sleep(2000);
		
		
		
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).sendKeys("");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).sendKeys("");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).sendKeys("");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).sendKeys("");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).sendKeys("");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).click();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).sendKeys("");
		
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).click();
		Thread.sleep(1000);
		
		
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).sendKeys("");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).click();
		Thread.sleep(1000);
		
		
		
		WebElement drpco7 = driver.findElement(By.id("shipping_country"));
		Select sel7 = new Select(drpco7);
		sel7.selectByValue("United Kingdom");
		Thread.sleep(2000);
		WebElement drpst7 = driver.findElement(By.id("shipping_state"));
		Select selsta7 = new Select(drpst7);
		selsta7.selectByValue("Aberdeen City");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).sendKeys("");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[normalize-space()='Place Order']")).click();
		Thread.sleep(20000);
		
		
		
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).clear();
		Thread.sleep(2000);
		
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).sendKeys("Shekh");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).sendKeys("Sajid");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).sendKeys("01632 960864");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).sendKeys("RugArtisan");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).sendKeys("71 Cherry Court ");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).sendKeys("SOUTHAMPTON");
		
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).sendKeys("southampton");
		Thread.sleep(2000);
		WebElement drpco8 = driver.findElement(By.id("shipping_country"));
		Select sel8 = new Select(drpco8);
		sel8.selectByValue("United Kingdom");
		Thread.sleep(2000);
		WebElement drpst8 = driver.findElement(By.id("shipping_state"));
		Select selsta8 = new Select(drpst8);
		selsta8.selectByValue("Hampshire");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).sendKeys("SO53 5PD");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[normalize-space()='Place Order']")).click();
		Thread.sleep(20000);
		
		
		
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(300);
		jse.executeScript("window.scrollBy(0,-100)");
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//input[@id='shipping[first_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[last_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[phone]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[company_name]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_0'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping_address_1'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[city]'])[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@id='shipping[postcode]'])[1]")).clear();
		Thread.sleep(2000);*/
		
	}

}
